# Generated by Django 5.2.7 on 2025-11-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EMAIL_VERIFICATION', 'Email Verification'), ('RESET_PASSWORD', 'Reset Password'), ('EXPO_REMINDER', 'Expo Reminder'), ('EVENT_REMINDER', 'Event Reminder'), ('QR_ISSUED', 'Qr Issued'), ('QR_REISSUED', 'Qr Reissued'), ('PAYMENT_COMPLETE', 'Payment Complete'), ('EXPO_STATUS_CHANGE', 'Expo Status Change'), ('AD_STATUS_CHANGE', 'Ad Status Change'), ('RESERVATION_CONFIRM', 'Reservation Confirm')], max_length=20)),
                ('file_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'MessageTemplate',
            },
        ),
    ]
