# Generated by Django 5.2.7 on 2025-11-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
